language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: cz+wA4rJzqAMgSh7m6DR10krcKDd0ZznHalFR9cH72HA0PKbGfI4CV+6Ox6ncrWCvnk4D/0P9eexKcQS/fOInPTQ6eeLPBK/a0RJrlLfBoPQr7FLgVn/oCgs314rvBsV1kq10tvtwmaBMyHAymllO6Iy2BocYYRmJK4IGB7F8cHjnQu0jVMg6IIm+QCSOGmr24TqekZyHGLUZ6M8LGJr2BszO4GGUebkvr7up/JsAKVaZgwD3cegNrf1PcfTjDppj5YmE5vKCMnDnid4vnYEO2X/lsw3ZWd4vR9eyLwAQSz2aCnoJhMx/aE/7E69JMEgGwHJ6ecYHGzweWM6B2tDhuxMHj29/sR8Vo9CXyBv0fqHTSGcULFIATxqveymAN3g7wCmcYZdp12ehzonJ5o9kwsaLCiQbxV/8aLc0zNdMHYwl4/YtuPoluPmiFyKLcOczAATozLjEyBRawxSW1z+Trk6FqSkY0i0TyqURNw+eOBiFV9H0EbnuErVTT8Snmas+FquoT8qHI/QQPOFpd2BmmWdUcos7uS40ZOe0V7Tw/REKeqjjb7DQJMQk6MVxInOm9OYNzQ6F73yM7sLoJsZDa7NXlJjwP8M5PaCqR5kGTtKrVTV4jd/bOJO6vz7TgUNLk7SJnLQkyxtQjN5OjH57UjCCLXNQTkzirCHLX5M+Xo=
  app: thawing-retreat-18752
  on:
    repo: Cohort-9/todo-ramon-colin
